filetype on             " Automatically detect file types
filetype plugin on      " Enable loading of plugin files for specific file types
filetype indent on      " Enable loading of indent file for specific file types
set nocompatible        " No vi compatibility

" Add recently accessed projects menu (project plugin)
set viminfo^=\!

" Minibuffer Explorer Settings
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" alt+n or alt+p to navigate between entries in QuickFix
map <silent> <m-p> :cp <cr>
map <silent> <m-n> :cn <cr>

" Change which file opens after executing :Rails command
let g:rails_default_file='config/database.yml'

syntax enable

set confirm             " Enable error files & error jumping
set clipboard+=unnamed  " Yanks go on clipboard instead
set history=256         " Number of things to remember in history
set autowrite           " Writes on make/shell commands
set ruler               " Ruler on
set number              " Line numbers on
set nowrap              " Line wrapping off
set timeoutlen=250      " Time to wait after ESC (default causes an annoying delay)

" Formatting
set tabstop=4           " <Tab> counts for 4 spaces
set backspace=2         " Backspace over indent, eol, start in insert mode
set cinoptions=:0,p0,t0
set cinwords=if,else,while,do,for,switch,case
set formatoptions=tcqr
set cindent
set autoindent          " Copy indent from current line when starting a new line
set smartindent         " Do smart autoindenting when starting a new line
set shiftwidth=4        " Number of spaces for autoindent and smartindent
set smarttab            " Improve use of <Tab> at beginning of line
"set expandtab          " Uncomment this to use spaces instead of tabs
" Display cursor before a tab in normal mode
set list lcs=tab:\ \ 

" Searching
set nocp incsearch      " Not in compatibility mode, no incremental searching
set hlsearch            " Highlight all search results
" Press Space to turn off highlighting and clear any message already displayed.
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" Visual
set showmatch           " Show matching brackets
set mat=5               " Bracket blinking
set novisualbell        " No blinking
set noerrorbells        " No noise
" statusline - lifted from http://albertwu.org/cs61a/notes/vimrc
set laststatus=2
set statusline=%.40F\ (%{&ff})\ %=%m\ %Y\ Line\ %l/%L,\ Column\ %v\ [%3p%%]

" Mouse stuff
set mousehide           " Hide mouse after chars typed
set mouse=              " Disable mouse

" Scrolling
set nostartofline
