# Grep colors
export GREP_OPTIONS='--color=auto'

# Aliases
alias chrome='open -a Google\ Chrome'
alias firefox='open -a Firefox'
alias ls='ls -G'
alias subl='open -a Sublime\ Text\ 2'

# Pager
export PAGER=less
export LESS=-R
